################################################################################################################################################
#############################################              测试环境            ##################################################################
################################################################################################################################################
####################################
#        embedded tomcat配置       #
####################################
server:
  port: 9101
  servlet:
    ##session配置
    session:
      timeout: 86400 #设置为1天
    #设置session超时时间，默认30min,最短1min,设置 单位是秒




spring:
  ####################################
  #            session配置           #
  ####################################
  session:
    #存放session的位置
    store-type: none


####################################
#          logback日志配置          #
####################################
logging:
  config: classpath:logback-spring-dev.xml
#  level:

####################################
#            dubbo配置           #
####################################
dubbo:
  application:
    name: cj-dubbo-provider
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: cj.springboot2.dubbo.provider.service
  registry:
    address:  nacos://172.16.207.221:8848
  monitor:
    protocol: registry #使用registry自动查找monitor

