################################################################################################################################################
#############################################              测试环境            ##################################################################
################################################################################################################################################

####################################
#        embedded tomcat配置       #
####################################
server:
  port: 9003
  servlet:
    ##session配置
    session:
      timeout: 86400 #设置为1天
    #设置session超时时间，默认30min,最短1min,设置 单位是秒

####################################
#             默认错误信息获取      #
####################################
  error:
#    默认报错信息中包含校验错误
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true
    include-message: always




spring:
####################################
#            session配置           #
####################################
  session:
    #存放session的位置
    store-type: none
  redis:
    host: 172.16.207.221
    port: 6379
    database: 0
    connect-timeout: 1800000
    lettuce:
      pool:
        min-idle: 0
        max-idle: 5 #处于idle状态的最大连接数
        max-wait: -1 #最大等待事件
        max-active: 20 #最大连接数

####################################
#           redis配置          #
####################################

####################################
#          logback日志配置          #
####################################
logging:
  config: classpath:logback-spring-dev.xml
#  level:

