################################################################################################################################################
#############################################              测试环境            ##################################################################
################################################################################################################################################

####################################
#        embedded tomcat配置       #
####################################
server:
  port: 9001
  servlet:
    ##session配置
    session:
      timeout: 86400 #设置为1天
    #设置session超时时间，默认30min,最短1min,设置 单位是秒

####################################
#             默认错误信息获取      #
####################################
  error:
#    默认报错信息中包含校验错误
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true
    include-message: always




spring:
####################################
#            session配置           #
####################################
  session:
    #存放session的位置
    store-type: none



####################################
#          logback日志配置          #
####################################
logging:
  config: classpath:logback-spring-dev.xml
#  level:

